name: WhatsApp Bot

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # run bot (this must stay running for QR)
      - run: node index.js
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
